# Site settings
title:       Estribancus - Es blog de'n Pere Vilàs
email:       pvilas@gmail.com
name: 		 Estribancus
description: "Blog de'n Pere Vilás. Hi ha coses de programació, espai, recetes i altres coses que m'interessan"
baseurl:     ""
# url:         "http://pvilas.com"
date_format: "%-d %b %Y"

# els permalinks els posam a l'estil de blogger per mantenir els links
permalink: ./:year/:month/:title.html


# Google services
google_analytics:
google_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments: 
facebook_appid: 
facebook_comments_number: 10

# Social icons
github_username: pvilas
bitbucket_username:
stackoverflow_id: pvilas
twitter_username: perevilas
google_plus_id: pvilas
linkedin_username: pvilas
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false



# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
# permalink:    pretty
paginate:     4
sass:
  compressed: true
